# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=200)),
                ('Program', models.CharField(max_length=200)),
                ('Section', models.CharField(max_length=200)),
                ('Section_Number', models.CharField(max_length=200)),
                ('Contents', models.CharField(max_length=200)),
                ('Attachments', models.CharField(max_length=200)),
                ('Plan_Page', models.CharField(max_length=200)),
                ('Page_No', models.CharField(max_length=200)),
                ('Effective_Date', models.CharField(max_length=200)),
                ('ransmittal_Number', models.CharField(max_length=200)),
                ('Superseded1', models.CharField(max_length=200)),
                ('Superseded2', models.CharField(max_length=200)),
                ('Superseded3', models.CharField(max_length=200)),
                ('Superseded4', models.CharField(max_length=200)),
                ('Superseded5', models.CharField(max_length=200)),
                ('Superseded6', models.CharField(max_length=200)),
                ('Superseded7', models.CharField(max_length=200)),
            ],
        ),
    ]
