# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatePlan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='ransmittal_Number',
        ),
        migrations.AddField(
            model_name='record',
            name='Transmittal_Number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Attachments',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Contents',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Effective_Date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Page_No',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Plan_Page',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Program',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Section',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Section_Number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Superseded1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Superseded2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Superseded3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Superseded4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Superseded5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Superseded6',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Superseded7',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
