# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatePlan', '0002_auto_20160731_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentPages_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=200, null=True)),
                ('Services', models.CharField(max_length=200, null=True)),
                ('ProgramServiceSubject', models.CharField(max_length=200, null=True)),
                ('Section', models.CharField(max_length=200, null=True)),
                ('SectionItem', models.CharField(max_length=200, null=True)),
                ('Contents', models.CharField(max_length=200, null=True)),
                ('StatePlanSection', models.CharField(max_length=200, null=True)),
                ('PlanPage', models.CharField(max_length=200, null=True)),
                ('pdfPageNumber', models.CharField(max_length=200, null=True)),
                ('EffectiveDate', models.CharField(max_length=200, null=True)),
                ('TransmittalNumber', models.CharField(max_length=200, null=True)),
                ('Superseded1', models.CharField(max_length=200, null=True)),
                ('Superseded2', models.CharField(max_length=200, null=True)),
                ('Superseded3', models.CharField(max_length=200, null=True)),
                ('Superseded4', models.CharField(max_length=200, null=True)),
                ('Superseded5', models.CharField(max_length=200, null=True)),
                ('Superseded6', models.CharField(max_length=200, null=True)),
                ('Superseded7', models.CharField(max_length=200, null=True)),
                ('Superseded8', models.CharField(max_length=200, null=True)),
                ('Superseded9', models.CharField(max_length=200, null=True)),
                ('Superseded10', models.CharField(max_length=200, null=True)),
                ('Superseded11', models.CharField(max_length=200, null=True)),
                ('Superseded12', models.CharField(max_length=200, null=True)),
                ('Superseded13', models.CharField(max_length=200, null=True)),
                ('Superseded14', models.CharField(max_length=200, null=True)),
                ('Superseded15', models.CharField(max_length=200, null=True)),
                ('Superseded16', models.CharField(max_length=200, null=True)),
                ('Superseded17', models.CharField(max_length=200, null=True)),
                ('Superseded18', models.CharField(max_length=200, null=True)),
                ('Superseded19', models.CharField(max_length=200, null=True)),
                ('Superseded20', models.CharField(max_length=200, null=True)),
                ('Superseded21', models.CharField(max_length=200, null=True)),
                ('Superseded22', models.CharField(max_length=200, null=True)),
                ('Superseded23', models.CharField(max_length=200, null=True)),
                ('Superseded24', models.CharField(max_length=200, null=True)),
                ('Superseded25', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TMACSP_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SPA_BSP', models.CharField(max_length=200, null=True)),
                ('Subject_Population', models.CharField(max_length=200, null=True)),
                ('Program_Category', models.CharField(max_length=200, null=True)),
                ('Services_Requirements', models.CharField(max_length=200, null=True)),
                ('Section', models.CharField(max_length=200, null=True)),
                ('StatePlanSection', models.CharField(max_length=200, null=True)),
                ('SectionItem', models.CharField(max_length=200, null=True)),
                ('Contents', models.CharField(max_length=200, null=True)),
                ('PlanPage', models.CharField(max_length=200, null=True)),
                ('pdfPage', models.CharField(max_length=200, null=True)),
                ('EffectiveDate', models.CharField(max_length=200, null=True)),
                ('TransmittalNumber', models.CharField(max_length=200, null=True)),
                ('Superseded', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
